### ISSUE TITLE
Support common package prefixes in object files

### ISSUE THREAD

**Issue by sgraf812** [ggreif/dynamic-loader#8]
The new `loadArchiveFromPath` is a good step in the right direction, but `stack` and `cabal` prefix every symbol with something dependent on their ~~`GhcPkgId` (consisting of package name, version and compilation fingerprint)~~ `package-key`/installed `package-id`. Some example object file (where I obtained `Version.o` by `stack ghc -- Version.hs`):

```
$ nm -j Version.o
_SuC_srt
_Version_version_closure
___stginit_Version
_ghczmprim_GHCziTypes_Izh_static_info
```

```
$ stack build
...
$ nm -j .stack-work/dist/.../build/libHSlambdamon-dll-0.1.0.0-328ABtogHCk5pzNMFqcjQG.a
...
.stack-work/dist/x86_64-osx/Cabal-1.22.5.0/build/libHSlambdamon-dll-0.1.0.0-328ABtogHCk5pzNMFqcjQG.a(Version.o):
_SvV_srt
___stginit_lambdzu328ABtogHCk5pzzNMFqcjQG_Version
_ghczmprim_GHCziTypes_Izh_static_info
_lambdzu328ABtogHCk5pzzNMFqcjQG_Version_version_closure
...
```

```
$ cabal install -j
...
$ nm -j dist/dist-sandbox-3f212c1c/build/libHSlambdamon-dll-0.1.0.0-1s5RQOsxzwl9inIbx4QsS6.a
...
dist/dist-sandbox-3f212c1c/build/libHSlambdamon-dll-0.1.0.0-1s5RQOsxzwl9inIbx4QsS6.a(Version.o):
_SHn_srt
___stginit_lambdamonzmdllzm0zi1zi0zi0zm1s5RQOsxzzwl9inIbx4QsS6_Version
_cHd_str
_cHh_str
_ghczmprim_GHCziTypes_Izh_static_info
_ghczmprim_GHCziTypes_Module_static_info
_ghczmprim_GHCziTypes_TrNameS_static_info
_lambdamonzmdllzm0zi1zi0zi0zm1s5RQOsxzzwl9inIbx4QsS6_Version_version_closure
_lambdamonzmdllzm0zi1zi0zi0zm1s5RQOsxzzwl9inIbx4QsS6_Version_zdtrModule1_closure
_lambdamonzmdllzm0zi1zi0zi0zm1s5RQOsxzzwl9inIbx4QsS6_Version_zdtrModule2_closure
_lambdamonzmdllzm0zi1zi0zi0zm1s5RQOsxzzwl9inIbx4QsS6_Version_zdtrModule_closure
...
```

For my current toy project, I have a custom Makefile which strips off prefixes containing the fingerprint (here the z-encoded form of 328ABtogHCk5pzNMFqcjQG) with `objcopy --redefine-syms`, but obviously that makefile isn't really pretty. I think we could parse out that fingerprint with a regex or something and maybe be smart about it from the loader side of things instead of just failing when we can't find the symbol verbatim. I wonder how GHCi handles this.

**Edit:** I just realized that `stack` prefixes names by `package-key` (as in `ghc-pkg dump | grep "key:"`), whereas `cabal` seems to use the installed `package-id` (IPID, `ghc-pkg dump | grep "id:"`). This kind of info is really toilsome to dig up. Though the naming scheme seems to change with recent GHC versions. [This](https://ghc.haskell.org/trac/ghc/wiki/Commentary/Packages/Concepts) should clarify nomenclature.

**Comment by sgraf812** [comment]
I guess matching based on a regex isn't really possible, since we don't have access to loaded symbols. I wonder if there's an RTS function for that...

**Comment by ggreif** [comment]
I am pretty sure http://github.com/ezyang will produce an answer.

**Comment by sgraf812** [comment]
(CCing @ezyang)

**Comment by ezyang** [comment]
OK, let's see how I can help. I don't really know what DynamicLoader does though.

> stack and cabal prefix every symbol with something dependent on their

This is not a Stack/cabal-install-ism, it's a GHC-ism, and it depends on the version of GHC you are using.

In GHC 7.8 and earlier, the prefix is always going to be the z-encoded package identifier (https://ghc.haskell.org/trac/ghc/wiki/Commentary/Compiler/SymbolNames). In 7.10 it's going to be derived off of the package key (the `key` field in the package database entry). In 8.0 and beyond, it's going to be precisely the installed package ID (and the key ALWAYS matches the ipid; ghc-pkg will complain otherwise.)

> For my current toy project, I have a custom Makefile which strips off prefixes containing the fingerprint (here the z-encoded form of 328ABtogHCk5pzNMFqcjQG) with objcopy --redefine-syms, but obviously that makefile isn't really pretty. I think we could parse out that fingerprint with a regex or something and maybe be smart about it from the loader side of things instead of just failing when we can't find the symbol verbatim. I wonder how GHCi handles this.

Yeah, uh, you really shouldn't do that. The whole point of the prefix is so that foo-0.2-aaa can coexist peacefully with foo-0.2-bbb in the same executable. If you strip the prefix the symbols will collide and it won't work.

I'm not sure why GHCi would ever need to find a particular symbol. Everything is named the right thing, so if you load up the transitive graph of objects into memory everything should find everything else.

> I guess matching based on a regex isn't really possible, since we don't have access to loaded symbols. I wonder if there's an RTS function for that...

There is, but I doubt it's what you want here. (If you must, look in `rts/Linker.c`.

**Comment by sgraf812** [comment]
`dynamic-loader` is a thin wrapper around the GHC API that enables hot code loading, e.g. linking and calling object files, object archives and shared objects into a GHC Haskell process at runtime. It's the closest to `plugins` you can find that actually works.

So, given just an archive of a package such as `libHSlambdamon-dll-0.1.0.0-328ABtogHCk5pzNMFqcjQG.a` above, can you think of an elegant way to pull out a symbol such as `Version.version`? Would it be possible to deduce the installed package identifier from the object archive general?

**Comment by ezyang** [comment]
So, are you dead set against using interface files? Because they would tell you exactly what you need.

**Comment by sgraf812** [comment]
No, I'm not. It's rather that I'm not sure where to find the information I need. Thanks for the pointer!

**Comment by ezyang** [comment]
Out of curiosity, if there is like, a single function that this library provides, what is its type? (I'm trying to understand what this library is adding around the GHC API.)

**Comment by sgraf812** [comment]
It's basically a lighter version of [the `System.Plugins.Load` module of `plugins`](https://hackage.haskell.org/package/plugins-1.5.5.0) which works with current GHC versions.

I'm also not a maintainer, but I'm currently surveying the ecosystem in this space, ranging from interpreted style `hslua` and `hint` over configuration by dynamic recompilation used in `dyre` (à la `yi`, `xmonad) to actual hot code loading (like `hint`, but loading compiled binaries) as in `plugins` and `dynamic-loader`. 

Actual motivation is a typical plugin scenario: Enable third parties to extend your program without having the client to install a compiler toolchain.

Well, and meanwhile I get to know about how the GHC machinery works.

**Comment by ezyang** [comment]
> Actual motivation is a typical plugin scenario: Enable third parties to extend your program without having the client to install a compiler toolchain.

Aha! Does that mean, eventually, you don't want to use the GHC API? Then reading interface files isn't going to work very well, because the format is quite complicated and you basically should never try to parse it without the GHC API.

(I have more to say, but I'd like to see if I understood you correctly.)

**Comment by sgraf812** [comment]
Actually, I would be fine with the GHC API, as long as everything can be reasonably deployed with the application. That seems to be the case with this library (which uses the GHC API under the hood), but not so much with e.g. `hint`, which relies on some `settings` file to be present at the `ghc` package installation path.

I'm under the impression that parsing interface files with the GHC API is quite unobtrusive, so that would be fine.

**Comment by ezyang** [comment]
Some meta-advice: the amount of abstraction offered by the GHC API is basically non-existent, and you are best off getting comfortable with how the implementation details of how GHC goes about doing things if you want to get anything done.

So, there are two ways this can go. One is to take the attitude that all the things you've asked for here are things that *should* be offered by the GHC API, and offer a patchset to GHC to make this easy to do (while at the same time making sure that it fits with how everything works today.) Two is to piecemeal pull together all the bits you need to do the particular thing you want to do. (It will probably stop working on the next GHC release.) For the piecemeal approach, the thing you want to do is "find the name of the symbol for a function named 'foo' in module 'Foo', a library 'libbar.a'", you need a way of determining the symbol name prefix. In GHC, the only way we know where the library comes from is from the package database, which records the prefix, so we always know what it should be. If you don't have a package database, but you know where the interface files are you can read it out from their; another approach is that the name of the library file should be related to the library naming. However, that is a Stack/cabal-install specific-ism.
